### ISSUE TITLE
AWS Credential Issue Hanging

### ISSUE THREAD

**Issue by tigerpeng2001** [hashicorp/learn-terraform#40] opened 2023-12-15 22:19 UTC
Hello,

Playing with TFC, I noticed when there was an issue with AWS credentials, I used short-lived credentials (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_SESSION_TOKEN). The terraform plan just hung there without showing any clue what was wrong.

Raw log downloaded:

Terraform v1.6.2
on linux_amd64
Initializing plugins and modules...
{"@level":"info","@message":"Terraform 1.6.2","@module":"terraform.ui","@timestamp":"2023-12-15T21:14:55.531419Z","terraform":"1.6.2","type":"version","ui":"1.2"}

------------ System Message ------------
Force cancel received. The operation will now be aborted.
----------------------------------------

------------ System Message ------------
Force cancel received. The operation will now be aborted.
----------------------------------------

------------ System Message ------------
Force cancel received. The operation will now be aborted.
----------------------------------------

------------ System Message ------------
Force cancel received. The operation will now be aborted.
----------------------------------------

**Comment by ritsok** [comment] 2024-05-03 18:18
Hi @tigerpeng2001, my best guess is that this may have been caused by session expiry. One potential solution to try in your own organization is using [dynamic credentials](https://developer.hashicorp.com/terraform/tutorials/cloud/dynamic-credentials).

Closing since this is a user-side credential error!

**Closed by ritsok** 2024-05-03 18:18 UTC
